name: Terraform Format Check

on:
  push:
    branches:
      - ci
  pull_request:
    branches:
      - ci

jobs:
  format_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.3.3
    - name: Terraform fmt check
      run: terraform fmt -check -recursive

